import ImgLogo from "../../assets/images/img-logo.png";
import ImgLandingLeft from "../../assets/images/img-landing-left.png";
import ImgLandingRight from "../../assets/images/img-landing-right.png";
import ImgLanding from "../../assets/images/img-landing.png";
import ImgMisiKita from "../../assets/images/img-mission.png";
import ImgFlow from "../images/img-flow.png";
import ImgTumpukan from "../images/img-tumpukan.png";
import ImgSungai from "../images/img-sungai.png";
import ImgPantai from "../images/img-pantai.png";
import ImgWhiteLogo from "../images/img-white-logo.png";
import ImgHeroOne from "../images/img-hero-1.png";
import ImgHeroTwo from "../images/img-hero-2.png";
import ImgHeroThree from "../images/img-hero-3.png";
import ImgAksi from "../images/img-aksi.png";
import ImgHeroArtikel from "./img-hero-artikel.png";
import ImgCardArtikel from "./img-artikel.png";
import ImgAksiTwo from "./img-aksi-two.png";
import ImgAksiThree from "./img-aksi-three.png";

export { ImgLogo, ImgLandingLeft, ImgLandingRight, ImgLanding, ImgMisiKita, ImgFlow, ImgPantai, ImgSungai, ImgTumpukan, ImgWhiteLogo, ImgAksiTwo, ImgHeroOne, ImgAksiThree, ImgHeroTwo, ImgHeroThree, ImgAksi, ImgHeroArtikel, ImgCardArtikel };
